steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/$_GCR_IMAGE',
        '-f',
        '$_DOCKERFILE_PATH',
        '.',
      ]

images:
  - 'gcr.io/$PROJECT_ID/$_GCR_IMAGE'
